import React, { useState } from 'react';
import { Download, FileText, Check, X, Printer, Shield, Sparkles, CheckCircle2 } from 'lucide-react';
import { jsPDF } from 'jspdf';
import { LegalDocument } from '../types/legal';

interface ExportCenterModalProps {
  isOpen: boolean;
  onClose: () => void;
  document: LegalDocument;
}

export const ExportCenterModal: React.FC<ExportCenterModalProps> = ({
  isOpen,
  onClose,
  document,
}) => {
  const [selectedFormat, setSelectedFormat] = useState<'pdf' | 'md' | 'txt'>('pdf');
  const [selectedTopic, setSelectedTopic] = useState<'summary' | 'brief' | 'checklist'>('summary');
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const handleExport = () => {
    let content = '';
    const footerText = '\n\nGenerated by LegalLens AI for informational purposes only. This output is not legal advice.';

    if (selectedTopic === 'summary') {
      content = `# Document Summary: ${document.title}
Parties: ${document.overview.parties.join(' & ')}
Effective Date: ${document.overview.effectiveDate}

## 1. What is this document?
${document.executiveSummary.whatIsThis}

## 2. Who are the parties?
${document.executiveSummary.parties}

## 3. What is the purpose?
${document.executiveSummary.purpose}

## 4. What does each party agree to do?
${document.executiveSummary.obligations}

## 5. What money is involved?
${document.executiveSummary.financialTerms}

## 6. How can the agreement end?
${document.executiveSummary.termination}

## 7. What should I review carefully?
${document.executiveSummary.reviewCarefully}
${footerText}`;
    } else if (selectedTopic === 'brief') {
      content = `# Lawyer Consultation Brief: ${document.title}
Generated Date: ${new Date().toLocaleDateString()}

## Priority Attention Items:
${document.attentionItems.map(a => `- [${a.level}] ${a.title} (${a.sourceSection}, Pg ${a.sourcePage}): ${a.observation}`).join('\n')}

## Suggested Questions for Attorney:
${document.clauses.flatMap(c => c.questionsToConsider).slice(0, 5).map((q, i) => `${i + 1}. ${q}`).join('\n')}
${footerText}`;
    } else {
      content = `# Legal Action Plan Checklist: ${document.title}
- [ ] Calendar initial review milestones
- [ ] Review proprietary intellectual property boundaries
- [ ] Schedule consultation with legal counsel
${footerText}`;
    }

    if (selectedFormat === 'pdf') {
      const pdf = new jsPDF();
      pdf.setFontSize(16);
      pdf.setTextColor(15, 23, 42);
      pdf.text(`LEGALLENS AI — ${selectedTopic.toUpperCase()}`, 14, 20);

      pdf.setFontSize(10);
      pdf.setTextColor(71, 85, 105);
      pdf.text(`Document: ${document.title}`, 14, 28);
      pdf.text(`Generated: ${new Date().toLocaleDateString()}`, 14, 34);

      pdf.line(14, 38, 196, 38);

      pdf.setFontSize(9);
      pdf.setTextColor(30, 41, 59);
      const split = pdf.splitTextToSize(content, 180);
      pdf.text(split, 14, 46);

      pdf.save(`LegalLens_${selectedTopic}_${document.title.replace(/\s+/g, '_')}.pdf`);
    } else if (selectedFormat === 'md') {
      const blob = new Blob([content], { type: 'text/markdown' });
      const url = URL.createObjectURL(blob);
      const a = window.document.createElement('a');
      a.href = url;
      a.download = `LegalLens_${selectedTopic}.md`;
      a.click();
    } else {
      const blob = new Blob([content], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = window.document.createElement('a');
      a.href = url;
      a.download = `LegalLens_${selectedTopic}.txt`;
      a.click();
    }

    onClose();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/80 backdrop-blur-sm p-4">
      <div className="bg-slate-900 border border-slate-800 rounded-2xl w-full max-w-lg p-6 space-y-6 shadow-2xl text-left">
        <div className="flex items-center justify-between pb-4 border-b border-slate-800">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-lg bg-indigo-500/20 flex items-center justify-center text-indigo-400">
              <Download className="w-4 h-4" />
            </div>
            <div>
              <h2 className="text-base font-bold text-white">Export Center</h2>
              <p className="text-xs text-slate-400">Export verified document intelligence and consultation materials.</p>
            </div>
          </div>
          <button onClick={onClose} className="text-slate-400 hover:text-white">
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Option 1: Select Topic */}
        <div className="space-y-2">
          <label className="text-xs font-semibold text-slate-300">Choose Export Content</label>
          <div className="grid grid-cols-3 gap-2">
            {[
              { id: 'summary', label: '📄 Executive Summary' },
              { id: 'brief', label: '👨‍⚖️ Lawyer Brief' },
              { id: 'checklist', label: '⏰ Action Plan' },
            ].map((t) => (
              <button
                key={t.id}
                onClick={() => setSelectedTopic(t.id as any)}
                className={`p-3 rounded-xl border text-xs font-semibold transition text-center cursor-pointer ${
                  selectedTopic === t.id
                    ? 'bg-indigo-600 text-white border-indigo-500 shadow'
                    : 'bg-slate-950 border-slate-800 text-slate-300 hover:bg-slate-800'
                }`}
              >
                {t.label}
              </button>
            ))}
          </div>
        </div>

        {/* Option 2: Select Format */}
        <div className="space-y-2">
          <label className="text-xs font-semibold text-slate-300">Select File Format</label>
          <div className="grid grid-cols-3 gap-2">
            {[
              { id: 'pdf', label: 'PDF Document (.pdf)' },
              { id: 'md', label: 'Markdown (.md)' },
              { id: 'txt', label: 'Plain Text (.txt)' },
            ].map((f) => (
              <button
                key={f.id}
                onClick={() => setSelectedFormat(f.id as any)}
                className={`p-3 rounded-xl border text-xs font-semibold transition text-center cursor-pointer ${
                  selectedFormat === f.id
                    ? 'bg-purple-600 text-white border-purple-500 shadow'
                    : 'bg-slate-950 border-slate-800 text-slate-300 hover:bg-slate-800'
                }`}
              >
                {f.label}
              </button>
            ))}
          </div>
        </div>

        {/* Disclaimer note */}
        <div className="p-3 bg-slate-950 rounded-xl border border-slate-800 text-[11px] text-slate-400">
          Exports automatically include source citations and statutory disclaimer:
          <span className="italic block text-slate-300 mt-1">
            "Generated by LegalLens AI for informational purposes only. This output is not legal advice."
          </span>
        </div>

        {/* Actions */}
        <div className="flex items-center justify-end gap-3 pt-2">
          <button
            onClick={onClose}
            className="px-4 py-2 rounded-xl text-xs font-semibold text-slate-400 hover:text-white"
          >
            Cancel
          </button>
          <button
            onClick={handleExport}
            className="px-5 py-2 rounded-xl text-xs font-semibold text-white bg-indigo-600 hover:bg-indigo-500 shadow-md shadow-indigo-600/30 transition flex items-center gap-1.5 cursor-pointer"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Download {selectedFormat.toUpperCase()}</span>
          </button>
        </div>
      </div>
    </div>
  );
};
