import React, { useState } from 'react';
import {
  Briefcase,
  Download,
  Copy,
  Check,
  Printer,
  Sparkles,
  ExternalLink,
  Shield,
  FileText
} from 'lucide-react';
import { jsPDF } from 'jspdf';
import { LegalDocument } from '../types/legal';
import { LegalImages } from '../assets/images';

interface LawyerBriefModalProps {
  document: LegalDocument;
  onClose?: () => void;
  onJumpToEvidence: (page: number, section: string) => void;
}

export const LawyerBriefModal: React.FC<LawyerBriefModalProps> = ({
  document,
  onClose,
  onJumpToEvidence,
}) => {
  const [copied, setCopied] = useState(false);
  const [isGeneratingPdf, setIsGeneratingPdf] = useState(false);

  const handleDownloadPdf = () => {
    setIsGeneratingPdf(true);
    try {
      const doc = new jsPDF();
      
      // Header
      doc.setFontSize(18);
      doc.setTextColor(30, 41, 59);
      doc.text('LEGALLENS AI — LAWYER CONSULTATION BRIEF', 14, 20);

      doc.setFontSize(10);
      doc.setTextColor(100, 116, 139);
      doc.text(`Document: ${document.title}`, 14, 28);
      doc.text(`Generated: ${new Date().toLocaleDateString()} · Client Prep Dossier`, 14, 34);

      // Horizontal line
      doc.setDrawColor(203, 213, 225);
      doc.line(14, 38, 196, 38);

      let yPos = 46;

      // Section 1: Overview
      doc.setFontSize(12);
      doc.setTextColor(15, 23, 42);
      doc.text('1. Overview & Parties', 14, yPos);
      yPos += 6;

      doc.setFontSize(9);
      doc.setTextColor(51, 65, 85);
      doc.text(`Parties: ${document.overview.parties.join(' & ')}`, 14, yPos);
      yPos += 5;
      doc.text(`Effective Date: ${document.overview.effectiveDate} | Expiration: ${document.overview.expirationDate}`, 14, yPos);
      yPos += 5;
      doc.text(`Governing Law: ${document.overview.governingLaw}`, 14, yPos);
      yPos += 10;

      // Section 2: Financial Terms
      doc.setFontSize(12);
      doc.setTextColor(15, 23, 42);
      doc.text('2. Financial & Compensation Provisions', 14, yPos);
      yPos += 6;

      doc.setFontSize(9);
      doc.setTextColor(51, 65, 85);
      const splitFin = doc.splitTextToSize(document.executiveSummary.financialTerms, 180);
      doc.text(splitFin, 14, yPos);
      yPos += splitFin.length * 5 + 6;

      // Section 3: Key Attention Items
      doc.setFontSize(12);
      doc.setTextColor(15, 23, 42);
      doc.text('3. Key Attention Items for Legal Review', 14, yPos);
      yPos += 6;

      doc.setFontSize(9);
      document.attentionItems.slice(0, 3).forEach((att) => {
        doc.setTextColor(194, 65, 12);
        doc.text(`• [${att.level}] ${att.title} (${att.sourceSection}, Pg ${att.sourcePage})`, 14, yPos);
        yPos += 5;
        doc.setTextColor(71, 85, 105);
        const splitReason = doc.splitTextToSize(`  Context: ${att.observation} Question: ${att.questionToConsider}`, 175);
        doc.text(splitReason, 16, yPos);
        yPos += splitReason.length * 4.5 + 4;
      });

      // Section 4: Questions for Attorney
      yPos += 2;
      doc.setFontSize(12);
      doc.setTextColor(15, 23, 42);
      doc.text('4. Formulated Questions for Attorney Consultation', 14, yPos);
      yPos += 6;

      doc.setFontSize(9);
      doc.setTextColor(51, 65, 85);
      const questions = document.clauses.flatMap(c => c.questionsToConsider).slice(0, 4);
      questions.forEach((q, i) => {
        const splitQ = doc.splitTextToSize(`${i + 1}. ${q}`, 180);
        doc.text(splitQ, 14, yPos);
        yPos += splitQ.length * 5 + 2;
      });

      // Footer
      doc.setFontSize(8);
      doc.setTextColor(148, 163, 184);
      doc.text('Disclaimer: Generated by LegalLens AI for informational and consultation-preparation purposes. Not legal advice.', 14, 285);

      doc.save(`LegalLens_Lawyer_Brief_${document.title.replace(/\s+/g, '_')}.pdf`);
    } catch (e) {
      console.error('PDF generation error', e);
    } finally {
      setIsGeneratingPdf(false);
    }
  };

  const handleCopyMarkdown = () => {
    const md = `# LegalLens AI — Lawyer Consultation Brief
**Document:** ${document.title}
**Parties:** ${document.overview.parties.join(' & ')}
**Effective Date:** ${document.overview.effectiveDate}
**Governing Law:** ${document.overview.governingLaw}

## 1. Executive Summary
${document.executiveSummary.whatIsThis}

## 2. Key Attention Items
${document.attentionItems.map(a => `- **[${a.level}] ${a.title}** (${a.sourceSection}, Pg ${a.sourcePage}): ${a.observation}\n  *Question to ask:* ${a.questionToConsider}`).join('\n')}

## 3. Financial Terms
${document.executiveSummary.financialTerms}

## 4. Prepared Questions for Legal Counsel
${document.clauses.flatMap(c => c.questionsToConsider).slice(0, 6).map((q, i) => `${i + 1}. ${q}`).join('\n')}

---
*Generated for informational and consultation-preparation purposes only. This output does not constitute formal legal representation or legal advice.*`;

    navigator.clipboard.writeText(md);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="w-full space-y-6 text-left pb-16">
      {/* Header Banner */}
      <div className="bg-slate-950 border border-slate-800 rounded-2xl p-6 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-indigo-500/15 border border-indigo-500/30 flex items-center justify-center text-indigo-400">
            <Briefcase className="w-5 h-5" />
          </div>
          <div>
            <h1 className="text-xl sm:text-2xl font-bold text-white">Prepare for a Legal Consultation</h1>
            <p className="text-xs text-slate-400">
              Executive briefing dossier formatted for productive discussion with a qualified legal professional.
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={handleCopyMarkdown}
            className="px-3.5 py-2 rounded-xl text-xs font-semibold bg-slate-900 hover:bg-slate-800 text-slate-200 border border-slate-800 transition flex items-center gap-1.5 cursor-pointer"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
            <span>{copied ? 'Copied' : 'Copy Markdown'}</span>
          </button>

          <button
            onClick={handleDownloadPdf}
            disabled={isGeneratingPdf}
            className="px-4 py-2 rounded-xl text-xs font-semibold text-white bg-indigo-600 hover:bg-indigo-500 shadow-md shadow-indigo-600/20 transition flex items-center gap-1.5 cursor-pointer disabled:opacity-50"
          >
            <Download className="w-3.5 h-3.5" />
            <span>{isGeneratingPdf ? 'Generating...' : 'Download PDF'}</span>
          </button>
        </div>
      </div>

      {/* Brief Dossier Card (Printable Layout) */}
      <div className="bg-slate-900/90 border border-slate-800 rounded-2xl p-6 sm:p-10 space-y-8 shadow-2xl">
        {/* Document Meta Header */}
        <div className="flex flex-col sm:flex-row justify-between items-start pb-6 border-b border-slate-800 gap-4">
          <div>
            <span className="text-[10px] font-bold tracking-widest text-indigo-400 uppercase">
              Client Consultation Briefing Dossier
            </span>
            <h2 className="text-xl sm:text-2xl font-black text-white mt-1">
              {document.title}
            </h2>
            <p className="text-xs text-slate-400 mt-1">
              Parties: {document.overview.parties.join(' & ')}
            </p>
          </div>
          <div className="text-right text-xs text-slate-400">
            <span className="font-semibold text-slate-200">Date Prepared:</span> {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
            <br />
            <span className="font-semibold text-slate-200">Jurisdiction:</span> {document.overview.governingLaw}
          </div>
        </div>

        {/* Section 1: Executive Overview */}
        <div className="space-y-2">
          <h3 className="text-xs font-bold uppercase tracking-wider text-indigo-400">
            1. Document Context & Business Purpose
          </h3>
          <p className="text-xs sm:text-sm text-slate-300 leading-relaxed bg-slate-950/60 p-4 rounded-xl border border-slate-800">
            {document.executiveSummary.purpose} {document.executiveSummary.obligations}
          </p>
        </div>

        {/* Section 2: Priority Focus Areas */}
        <div className="space-y-3">
          <h3 className="text-xs font-bold uppercase tracking-wider text-amber-400">
            2. Priority Clauses Deserving Legal Scrutiny
          </h3>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3 text-xs">
            {document.attentionItems.map((item) => (
              <div key={item.id} className="bg-slate-950 p-4 rounded-xl border border-slate-800 space-y-1.5">
                <div className="flex items-center justify-between">
                  <span className="font-bold text-slate-200">{item.title}</span>
                  <button
                    onClick={() => onJumpToEvidence(item.sourcePage, item.sourceSection)}
                    className="text-[10px] text-cyan-400 hover:underline flex items-center gap-1"
                  >
                    <span>Pg {item.sourcePage}</span>
                    <ExternalLink className="w-2.5 h-2.5" />
                  </button>
                </div>
                <p className="text-slate-400 leading-relaxed">{item.observation}</p>
                <p className="text-indigo-300 text-[11px] pt-1">
                  💡 <strong>Prompt for Counsel:</strong> {item.questionToConsider}
                </p>
              </div>
            ))}
          </div>
        </div>

        {/* Section 3: Financial & Termination Terms */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs">
          <div className="bg-slate-950 p-4 rounded-xl border border-slate-800 space-y-1.5">
            <h4 className="font-bold text-emerald-400 uppercase tracking-wider text-[11px]">
              3. Financial Terms
            </h4>
            <p className="text-slate-300 leading-relaxed">
              {document.executiveSummary.financialTerms}
            </p>
          </div>
          <div className="bg-slate-950 p-4 rounded-xl border border-slate-800 space-y-1.5">
            <h4 className="font-bold text-orange-400 uppercase tracking-wider text-[11px]">
              4. Termination & Notice Protocols
            </h4>
            <p className="text-slate-300 leading-relaxed">
              {document.executiveSummary.termination}
            </p>
          </div>
        </div>

        {/* Section 4: Questions for Attorney */}
        <div className="space-y-2">
          <h3 className="text-xs font-bold uppercase tracking-wider text-purple-400">
            5. Suggested Questions for Attorney Consultation
          </h3>
          <div className="bg-slate-950 p-4 rounded-xl border border-slate-800">
            <ol className="space-y-2 text-xs text-slate-300 list-decimal pl-4">
              {document.clauses.flatMap(c => c.questionsToConsider).slice(0, 6).map((q, idx) => (
                <li key={idx} className="leading-relaxed">{q}</li>
              ))}
            </ol>
          </div>
        </div>

        {/* Legal Disclaimer Footer */}
        <div className="pt-6 border-t border-slate-800 text-center text-[11px] text-slate-500 space-y-1">
          <p>
            Generated for informational and consultation-preparation purposes only. This document does not constitute legal representation or advice.
          </p>
          <p>© 2026 LegalLens AI · Evidence-Grounded Legal Intelligence</p>
        </div>
      </div>
    </div>
  );
};
